# Sam Pirkl

from socket import *

# set port number, IP, and TCP
server_port = 12000
server_socket = socket(AF_INET, SOCK_STREAM)

# bind the server to the port and have it listen indefinitely
server_socket.bind(("", server_port))
server_socket.listen(1)
print(f"The server is listening on port {server_port}")

while True:
    # make a connection socket for each client that connects
    connection_socket, addr = server_socket.accept()
    request = connection_socket.recv(1024).decode()

    try:
        # get the file name from the request
        file_name = request.split()[1]
        file_name = file_name.lstrip("/")

        # START OF CODE GENERATED BY GEMINI TO SUPPORT DIFFERENT CONTENT-TYPES
        ext = file_name.split(".")[-1].lower() if "." in file_name else ""

        # Map common extensions to Content-Type headers
        if ext in ["html", "htm"]:
            content_type = "text/html"
        elif ext == "png":
            content_type = "image/png"
        elif ext in ["jpg", "jpeg"]:
            content_type = "image/jpeg"
        elif ext == "gif":
            content_type = "image/gif"
        elif ext == "ico":
            content_type = "image/x-icon"
        elif ext == "css":
            content_type = "text/css"
        elif ext == "js":
            content_type = "application/javascript"
        else:
            content_type = "application/octet-stream"
        # END OF CODE GENERATED BY GEMINI

        # open the file given by the request and extract the html data
        with open(file_name, "r") as file:
            file_data = file.read()

        # make a response with the html data if the file exists
        response = (
            "HTTP/1.1 200 OK\r\n"
            f"Content-Type: {content_type}\r\n"
            f"Content-Length: {len(file_data)}\r\n"
            "Connection: close\r\n"
            "\r\n"
            f"{file_data}"
        )
    except:
        # return file not found if file doesnt exist
        body = "<html><body>404 File Not Found</body></html>"
        print(f"File not found {file_name}")
        response = (
            "HTTP/1.1 404 Not Found\r\n"
            "Content-Type: text/html\r\n"
            "Connection: close\r\n\r\n"
            f"{body}"
        )
        
    # send the response and close the socket for the particular client
    connection_socket.send(response.encode())
    connection_socket.close()
